# Site settings
title: Nautica
email: info@nauticashipping.co.nz
description: Nautica Shipping provides comprehensive expert shipping and logistics services for vehicles and automotive parts, agricultural equipment and machinery, household goods and furniture, construction and building materials, food products (including dry, chilled and frozen goods), health and cosmetic products and clothing and retail goods.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://nauticashipping.co.nz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
